
name: collaborative_task_manager
description: Application mobile de gestion de tâches collaboratives
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  provider: ^6.1.1
  
  # UI Components
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  fl_chart: ^0.65.0
  table_calendar: ^3.1.3
  
  # Utilities
  intl: ^0.19.0
  image_picker: ^1.1.2
  
  uuid: ^4.2.1
  
  # Notifications
  flutter_local_notifications: ^16.3.2
 
  recaptcha_enterprise_flutter: ^18.7.1
  http: ^1.4.0
  flutter_recaptcha_enterprise: ^0.1.0
  g_recaptcha_v3: ^1.0.0
  file_picker: ^10.2.0
  flutter_easy_recaptcha_v2: ^0.1.0
  firebase_core: ^3.15.1
  cloud_firestore: ^5.6.11
  firebase_auth: ^5.6.2
  firebase_storage: ^12.1.2
  image_picker_web: ^3.0.0
  universal_html: ^2.2.1
  syncfusion_flutter_charts: ^30.2.7
  google_sign_in: ^6.1.5
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    # - assets/icons/
    